# =================================================================================================
# Project: SCAN - Searching Chemical Actions and Networks
#          Hokkaido University (2021)
#          Last Update: Q2 2023
# ________________________________________________________________________________________________
# Authors: Mikael Nicander Kuwahara (Lead Developer) [2022-]
#          Jun Fujima (Former Lead Developer) [2021]
# ________________________________________________________________________________________________
# Description: This is the docker-compose file for the scan-app part of the SCAN project. 
#              (if ever run on its on by itself, but it usually never does).
# ------------------------------------------------------------------------------------------------
# Notes: You only need to care about this if you ever wish to run this part of SCAN on its own.
# ------------------------------------------------------------------------------------------------
# References: 
# =================================================================================================

version: '3.5'
services:
  app:
    build: .
    image: jfujima/scan/app
    container_name: scan_app
    ports:
      - '0.0.0.0:80:3000'

networks:
  default:
    external:
      name: scan-network
