version: '3.5'
services:
  app:
    build: .
    image: jfujima/scan/app
    container_name: scan_app
    ports:
      - '0.0.0.0:80:3000'

networks:
  default:
    external:
      name: scan-network
