# =================================================================================================
# Project: SCAN - Searching Chemical Actions and Networks
#          Hokkaido University (2021)
#          Last Update: Q2 2023
# ________________________________________________________________________________________________
# Authors: NorthGrid (Support Dev)
#          Mikael Nicander Kuwahara (Lead Developer) [2022-]
#          Jun Fujima (Former Lead Developer) [2021]
# ________________________________________________________________________________________________
# Description: This is the Developer version of the Dockerfile for the scan-api-public part of 
#              the SCAN Project.
# ------------------------------------------------------------------------------------------------
# Notes: This was part of the NorthGrid Support in 2022 
# ------------------------------------------------------------------------------------------------
# References: 
# =================================================================================================

FROM python:3.8

LABEL maintainer "jfujima"
RUN set -ex \
  && apt-get update -y --fix-missing \
  && apt-get install -y -q --no-install-recommends \
  curl \
  file \
  && apt-get purge -y --auto-remove

# install
RUN pip install pipenv
ADD Pipfile Pipfile.lock /
RUN pipenv install --system

# add to application
# ADD app.py /
# ADD service service
# ADD scan_analytics scan_analytics
# ADD grrm grrm
# ADD sqlite.db sqlite.db
ADD keyfiles keyfiles

# ARG root_path=aaa
# ENV ROOT_PATH=$root_path

# RUN echo "${ROOT_PATH}"
RUN echo $PUBLIC_API_ROOT_PATH

EXPOSE 8000
#CMD ["uvicorn", "app:api", "--host", "0.0.0.0", "--port", "8000", "--root-path", "echo '/api'"]
CMD uvicorn app:api --host 0.0.0.0 --port 8000 --root-path $PUBLIC_API_ROOT_PATH --reload