# =================================================================================================
# Project: SCAN - Searching Chemical Actions and Networks
#          Hokkaido University (2021)
# ________________________________________________________________________________________________
# Authors: Jun Fujima (Former Lead Developer) [2021]
#          Mikael Nicander Kuwahara (Current Lead Developer) [2022-]
# ________________________________________________________________________________________________
# Description: This is the docker-compose file for the scan-mariadb database part of the SCAN 
#              project which defines those services and more that is required in order to run 
#              the DB.
# ------------------------------------------------------------------------------------------------
# Notes: You only need to care about this if you ever wish to run this part of SCAN on its own.
# ------------------------------------------------------------------------------------------------
# References: 
# =================================================================================================
version: '3.5'

services:
  # MySQL, MariaDB version
  db:
    build: ./docker/db
    container_name: mysql_host
    env_file:
      - .env
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/init:/docker-entrypoint-initdb.d
      - ./docker/db/scripts:/scripts
    ports:
      - 127.0.0.1:3306:3306
    networks:
      - scan-network
    user: '${USERID}:${GROUPID}'

  # phpMyAdmin
  phpmyadmin:
    container_name: test_phpmyadmin
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    ports:
      - 127.0.0.1:8080:80
    networks:
      - scan-network

networks:
  scan-network:
    name: scan-network
    driver: bridge
